### ISSUE TITLE
vless搭建失败

### ISSUE THREAD

**Issue by monsoon0505** [paniy/Xray_bash_onekey#16]
之前一直正常使用没问题，前天出现问题；手机v2rayng链接提示 失败 io: read/write on close pipe;
用最新版重新搭建，问题依旧；

Oracle cloud
ubuntu系统

**Comment by paniy** [comment]
按照你的描述，这应该不是脚本的问题。

**Comment by monsoon0505** [comment]
> 

大佬能否帮忙判断个方向；我和朋友都同时出现这个问题，重新搭建多次均无效；
过往搭建多次，比较熟练；
或者我能提供什么信息，可以更快定位问题，感谢

**Comment by paniy** [comment]
有可能是客户端DNS问题，有可能是域名被墙的问题等等。

**Comment by paniy** [comment]
在 https://github.com/paniy/Xray_bash_onekey/commit/232195443584186e568b3cfe2f48c5501d97c369 中增加了本地连通性测试，可以测试是否为服务端配置异常。

**Comment by monsoon0505** [comment]
> 在 [2321954](https://github.com/paniy/Xray_bash_onekey/commit/232195443584186e568b3cfe2f48c5501d97c369) 中增加了本地连通性测试，可以测试是否为服务端配置异常。

未联通，nginx未启动，我重建一个vps再试试，有问题我再更新，感谢

**Comment by monsoon0505** [comment]
已解决，最新版重新搭建都好了
