### ISSUE TITLE
用超级用户打开脚本时会出现死循环

### ISSUE THREAD

**Issue by skylayer** [paniy/Xray_bash_onekey#17]
`/bin/idleleo: line 2841: /tmp/version_cmp.tmp: Permission denied
/bin/idleleo: line 2842: /tmp/version_cmp.tmp: Permission denied
(standard_in) 1: syntax error
--2021-12-24 04:38:05--  https://raw.githubusercontent.com/paniy/Xray_bash_onekey/main/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 132499 (129K) [text/plain]
Saving to: ‘/etc/idleleo/install.sh’

install.sh                100%[=====================================>] 129.39K  --.-KB/s    in 0.002s  

Last-modified header missing -- time-stamps turned off.
2021-12-24 04:38:05 (54.1 MB/s) - ‘/etc/idleleo/install.sh’ saved [132499/132499]

[OK]  下载最新脚本 完成 `

**Comment by paniy** [comment]
原因在于：/tmp/version_cmp.tmp: Permission denied
无权访问 /tmp ，检查文件夹权限

**Comment by paniy** [comment]
在 https://github.com/paniy/Xray_bash_onekey/commit/bf4a310c6883c5be31bda0d7c9b416d91396ae20 中修改了此文件的位置与文件名，请注意。
