### ISSUE TITLE
编译nginx时设置的nginx.conf路径问题

### ISSUE THREAD

**Issue by 2826915729** [paniy/Xray_bash_onekey#18]
我这里查看到启动配置文件目录是在/etc/nginx/conf/nginx.conf
`--conf-path=/etc/nginx/nginx.conf`
导致使用nginx -s reload或者nginx -t等提示`/etc/nginx/nginx.conf not found`

**Comment by paniy** [comment]
尝试使用`systemctl start nginx`来启动nginx。
