### ISSUE TITLE
无法通过连通性测试的问题

### ISSUE THREAD

**Issue by AnkhWU** [paniy/Xray_bash_onekey#19]
您好，感谢您提供的脚本！
我在昨天(4月18日)尝试通过您的脚本配置完成ngix + ws + tls，即模式一，在运行状态一栏中，始终显示“连通性：无法连通”。
尝试重新安装脚本或者升级Xray均无效。系统版本为Ubuntu18.04，还请您提供指导，感谢!
![1650299957(1)](https://user-images.githubusercontent.com/49145574/163841181-09290e7f-885c-42d0-930d-96e44bf972a3.png)

**Comment by paniy** [comment]
如果能正常使用不用管它，这是本地测试，不一定准确。

**Comment by AnkhWU** [comment]
> 如果能正常使用不用管它，这是本地测试，不一定准确。

好的，谢谢~
