### ISSUE TITLE
使用脚本时退格键（BackSpace）无法正常起作用

### ISSUE THREAD

**Issue by zurica2013** [paniy/Xray_bash_onekey#21]
首先感谢大佬的脚本！
有一个小问题不知道能否该进：
我使用的SSH工具是MobaXterm，默认的终端设置选项里有“BackSpace sends ^H”，而脚本第四行是“stty erase ^?”。
结果就是脚本在运行中和运行后，退格键（BackSpace）都无法起作用，只能显示^H。小白一开始碰到这个问题还是很困惑的~~
假如终端默认设置了“erase = ^?”，那“stty erase ^?”似乎也没什么必要。
或者是这句还有其他用途？恳请大佬指教~~

**Comment by paniy** [comment]
确实，默认设置了“erase = ^?”，脚本的“stty erase ^?”是没必要的。这句本身是为了兼容某些终端的，考虑到你遇到的问题，我把这句注释掉。谢谢反馈。

**Comment by paniy** [comment]
https://github.com/paniy/Xray_bash_onekey/commit/95353eb64b3c2fe1e00e00411a54a08c34e6e1e9

**Comment by zurica2013** [comment]
感谢！
