### ISSUE TITLE
运行成功但是连接总是不成功

### ISSUE THREAD

**Issue by Angel0726** [paniy/Xray_bash_onekey#25]
<img width="494" alt="image" src="https://user-images.githubusercontent.com/32816780/195990473-42cd33b1-9c18-401b-85ef-8390b40165e5.png">
尝试了3、4、5全部尝试了且运行成功。但是只有模式5扫描二维码之后能够翻墙；3、4扫描二维码之后都不能进行翻墙

**Comment by paniy** [comment]
检查以下nginx是否正常在运行。

**Comment by Angel0726** [comment]
找到原因了。被封了
