### ISSUE TITLE
无法使用xtls协议，但是tls 协议正常

### ISSUE THREAD

**Issue by jiawen94** [paniy/Xray_bash_onekey#3]
我debian10选择安装 Xray (VLESS + TCP + XTLS / TLS + Nginx 及 VLESS + TCP + TLS + Nginx + WebSocket 回落并存模式)
![image](https://user-images.githubusercontent.com/29114225/112761993-50998380-9030-11eb-98ab-ff9bd6cba925.png)

服务端没有对应log的输出，客户端日志显示访问成功

**Comment by paniy** [comment]
暂时不支持两种方式同时共存。
