### ISSUE TITLE
安装失败。

### ISSUE THREAD

**Issue by 716c** [paniy/Xray_bash_onekey#5]
-- A start job for unit nginx.service has begun execution.
-- 
-- The job identifier is 1035.
Jul 11 17:12:32 beta nginx[46380]: nginx: [emerg] duplicate location "/data" in /etc/idleleo/conf/nginx/xray.conf:36
Jul 11 17:12:32 beta nginx[46380]: nginx: configuration file /etc/nginx/conf/nginx.conf test failed
Jul 11 17:12:32 beta systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStartPre= process belonging to unit nginx.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Jul 11 17:12:32 beta systemd[1]: nginx.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit nginx.service has entered the 'failed' state with result 'exit-code'.
Jul 11 17:12:32 beta systemd[1]: Failed to start The NGINX HTTP and reverse proxy server.
-- Subject: A start job for unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit nginx.service has finished with a failure.
-- 
-- The job identifier is 1035 and the job result is failed.
Jul 11 17:12:56 beta sshd[46629]: Received disconnect from 49.51.12.25 port 51022:11: Bye Bye [preauth]
Jul 11 17:12:56 beta sshd[46629]: Disconnected from authenticating user root 49.51.12.25 port 51022 [preauth]
Jul 11 17:17:01 beta CRON[49225]: pam_unix(cron:session): session opened for user root by (uid=0)
Jul 11 17:17:01 beta CRON[49233]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jul 11 17:17:01 beta CRON[49225]: pam_unix(cron:session): session closed for user root
Jul 11 17:17:43 beta sshd[49650]: Received disconnect from 121.4.127.97 port 48966:11: Bye Bye [preauth]
Jul 11 17:17:43 beta sshd[49650]: Disconnected from authenticating user root 121.4.127.97 port 48966 [preauth]

另外，脚本可以自定义安装路径吗？ 还有之前有证书的能不能不再申请了？

**Comment by paniy** [comment]
nginx配置有问题。不能自定义安装路径，可以不再申请，把证书重命名为xray.crt、xray.key并放入/etc/idleleo/cert就可以。

**Comment by 716c** [comment]
感谢回复。另外，可否加入上传自由证书选项以及能否加入kcptun？ 对游戏帮助很大。 谢谢！

**Comment by paniy** [comment]
> 感谢回复。另外，可否加入上传自由证书选项以及能否加入kcptun？ 对游戏帮助很大。 谢谢！

脚本上传证书麻烦而且会有安全问题。kcptun 暂时不考虑支持，根据 xray-core 作者自己的说法，适合游戏的协议会开发，现阶段支持意义不大，推荐直接ss。
![](https://raw.githubusercontent.com/paniy/selfuse/360cd376f139564f2f58dbd36d532f75e32a862b/JUNK/20210714222627.png)

**Comment by 716c** [comment]
明白了, 没及时看xray-xore的更新.
