### ISSUE TITLE
acme.sh被收购 更换默认证书颁发机构为ZeroSSL 还安全吗?

### ISSUE THREAD

**Issue by zswdcx** [paniy/Xray_bash_onekey#7]
2021年7月21日, 官方文档中已明确说明默认证书申请机构是ZeroSSL(在这之前没有明确说明)
acme.sh --set-default-ca  --server  letsencrypt

**Comment by paniy** [comment]
安全的问题一直都是个伪命题，除去你提到的CA本身是否安全的问题，算法、传输协议等等都会影响安全性。从现在量子计算机的发展看，现有的最常用的“安全”的算法被破解也只是时间问题。随便说一句，各国政府控制CA可能是个常规操作。。也就是可以直接中间人攻击你。所以，如何获得相对的安全，就看你想和那方“势力”为敌了哈哈。
