### ISSUE TITLE
[错误]  SSL 证书测试签发失败 -Connection refused

### ISSUE THREAD

**Issue by qnyblog** [paniy/Xray_bash_onekey#8]
使用的ip v6 vps, cloudflare dns, 请问如何解决，谢谢

[Wed Aug  4 01:49:23 UTC 2021] The domain key is here: /root/.acme.sh/xxx.xxx.net_ecc/xxx.xxx.net.key
[Wed Aug  4 01:49:23 UTC 2021] Single domain='xxx.xxx.net'
[Wed Aug  4 01:49:23 UTC 2021] Getting domain auth token for each domain
[Wed Aug  4 01:49:25 UTC 2021] Getting webroot for domain='xxx.xxx.net'
[Wed Aug  4 01:49:25 UTC 2021] Verifying: xxx.xxx.net
[Wed Aug  4 01:49:25 UTC 2021] Standalone mode server
[Wed Aug  4 01:49:27 UTC 2021] Pending, The CA is processing your order, please just wait. (1/30)
[Wed Aug  4 01:49:30 UTC 2021] xxx.xxx.net:Verify error:Fetching http://xxx.xxx.net/.well-known/acme-challenge/bdfxYdznQY8p60_RQ3G0-vRvb3fDdUnicK7Yx-2tIik: Connection refused
[Wed Aug  4 01:49:30 UTC 2021] Please add '--debug' or '--log' to check more details.
[Wed Aug  4 01:49:30 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[错误]  SSL 证书测试签发失败

**Comment by paniy** [comment]
显示无法通过80端口连接服务器

**Comment by qnyblog** [comment]
谢谢
